package nl.everlutions.wifichat.utils;

public interface Constants {

    boolean DEBUG_MODE = true;
    boolean DEBUG_LOG_API_CALLS = DEBUG_MODE;
    boolean CRASHLYTICS_ENABLED = false;
    boolean APPS_FLYER_ENABLED = false;

    boolean DEBUG_FRAGMENTS_LIFECYCLE = false; // set to FALSE for release

    /*  Feature Flags - Turn these on or off to enable in app-functionality */
    boolean FEATURE_BOTTLE_QUANTITY_ENABLED = false;
    boolean FEATURE_NEW_BOTTLES_ENABLED = false;

    long TIME_SECOND = 1000;
    long TIME_MINUTE = TIME_SECOND * 60;
    long TIME_HOUR = 60 * TIME_MINUTE;
    long TIME_DAY = 24 * TIME_HOUR;
    long TIME_WEEK = 7 * TIME_DAY;

    int IMAGE_PREFERRED_WIDTH = 480;
    int IMAGE_MAX_WIDTH = 600;

    String PREF_SETTINGS = "PREF_SETTINGS";

    String PREF_KEY_USER_NAME = "PREF_KEY_USER_NAME";
    String PREF_KEY_SELECTED_ADDRESS_DTO = "PREF_KEY_SELECTED_ADDRESS_DTO";
    String PREF_KEY_SELECTED_DEALER_DTO = "PREF_KEY_SELECTED_DEALER_DTO";
    String PREF_KEY_ACTIVE_ORDER_DTO = "PREF_KEY_ACTIVE_ORDER_DTO";
    String PREF_KEY_HOME_ADDRESS_DTO = "PREF_KEY_HOME_ADDRESS_DTO";

    String PREF_KEY_PHONE = "PREF_KEY_PHONE";
    String PREF_KEY_PHONE_AREA_CODE = "PREF_KEY_PHONE_AREA_CODE";
    String PREF_KEY_PAYMENT_TYPE = "PREF_KEY_PAYMENT_TYPE";
    String PREF_KEY_ADDTIONAL_ORDER_INFO = "PREF_KEY_ADDTIONAL_ORDER_INFO";
    String PREF_KEY_ADDTIONAL_ADDRESS_INFO = "PREF_KEY_ADDTIONAL_ADDRESS_INFO";
    String PREF_KEY_PUSH_IS_REGISTERED = "PREF_KEY_PUSH_IS_REGISTERED";
    String PREF_KEY_PUSH_RETRY_COUNT = "PREF_KEY_PUSH_RETRY_COUNT";
    String PREF_KEY_API_END_POINT = "PREF_KEY_API_END_POINT";
    String PREF_KEY_FACEBOOK_ASKED = "PREF_KEY_FACEBOOK_ASKED";
    String PREF_KEY_TERMS_AND_CONDITIONS_ASKED = "PREF_KEY_TERMS_AND_CONDITIONS_ASKED";
    String PREF_KEY_DUMMY_USER = "PREF_KEY_DUMMY_USER";
    String PREF_KEY_USER = "PREF_KEY_USER";
    String PREF_KEY_DEBUG_USE_IS_OPEN = "PREF_KEY_DEBUG_USE_IS_OPEN";
    String PREF_KEY_DEBUG_SHOW_MEM_VIEW = "PREF_KEY_DEBUG_SHOW_MEM_VIEW";
    String PREF_KEY_ORDER_DTO_LIST = "ORDER_LIST";
    String PREF_KEY_APP_VERSION_CODE = "PREF_KEY_APP_VERSION_CODE";
    String PREF_KEY_NOTIFY_ME_REGISTERED = "PREF_KEY_NOTIFY_ME_REGISTERED";
    String PREF_KEY_SORTING_TYPE = "PREF_KEY_SORTING_TYPE";


    String PREF_KEY_FILTER_SETTINGS = "PREF_KEY_FILTER_SETTINGS";
    String PREF_KEY_PRODUCT_TYPE = "PREF_KEY_PRODUCT_TYPE";
    String PREF_KEY_IS_REFILL = "PREF_KEY_IS_REFILL";
    String PREF_KEY_SORT_TYPE = "PREF_KEY_SORT_TYPE";

    // INTENT EXTRA KEYS
    String EXTRA_PUSH_MSG = "EXTRA_PUSH_MSG";
    String EXTRA_FILTER_SETTINGS = "EXTRA_FILTER_SETTINGS";
    String EXTRA_P45_IS_AVAILABLE = "EXTRA_P45_IS_AVAILABLE";

    String ACTION_ORDER_STATUS_UPDATE = "ACTION_ORDER_STATUS_UPDATE";

    String GA_APP_FIRST_STARTUP = "GA_APP_FIRST_STARTUP";
    String GA_FIRST_CONNECTION_SET = "GA_FIRST_CONNECTION_SET";
    String GA_DEALER_SORT_BY_DEFINED = "GA_DEALER_SORT_BY_DEFINED";
    String GA_DEALER_SORT_BY_CHOICE = "GA_DEALER_SORT_BY_CHOICE";
    String GA_DEALER_NAME = "GA_DEALER_NAME";
    String GA_IS_IN_DELIVERY_AREA = "GA_IS_IN_DELIVERY_AREA";
    String GA_IS_MY_LOCATION_USED = "GA_IS_MY_LOCATION_USED";

    //FIREBASE REMOTE CONFIG
    String RC_SHARE_MSG = "share_msg";
    String RC_SHARE_LINK = "share_link_android";
    String RC_SHARE_HASHTAGS = "share_hashtags";
    String RC_SHARE_QUOTE = "share_quote";
    String RC_ORDER_CANCEL_LEVEL = "order_cancel_level";
    String RC_DEFAULT_ADDRESS_STREET = "default_address_street";
    String RC_DEFAULT_ADDRESS_DISTRICT = "default_address_district";
    String RC_DEFAULT_ADDRESS_LAT = "default_address_lat";
    String RC_DEFAULT_ADDRESS_LON = "default_address_lon";


    int REQUEST_PERMISSION_LOCATION = 200;
    int REQUEST_PLAY_SERVICES_RESOLUTION = 9000;
    int REQUEST_UPATE_APP = 9001;
    int REQUEST_ORDER_STATUS_NOTIFICATION_ID = 7133;
    int REQUEST_ADDRESS_OBJECT = 201;
    int REQUEST_SHARE = 12392;
    int REQUEST_DEBUG_ACTIVITY = 301;


    int REQUEST_FILTER_SETTINGS = 444;
    int REQUEST_CHECKOUT_CHANGE_ORDER_DETAILS = 401;
    int REQUEST_CHECKOUT_CHANGE_ADDRESS = 402;
    int REQUEST_CHECKOUT_CHANGE_USER_INFO = 403;
}
